image: python:latest

stages:
  - test

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install pipenv
  - pipenv install --dev
  - cp test_project/settings.py.sample test_project/local_settings.py
  - sed -i -e "s/SECRET_KEY = '.*'/SECRET_KEY = '_'/" upperly/settings.py

test:
  stage: test
  script:
    - ./test_manage.py test
    - coverage run test_manage.py test handypackegs.tests -v 2
